### ISSUE TITLE
Runtime error for Chapel as a python library with CHPL_TASKS=fifo

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#16948]
### Summary of Problem

Chapel as a library encounters a runtime error when calling the runtime initialization while `CHPL_TASKS=fifo`.

I did not see this error when compiling as a library and using it from C.

### Steps to Reproduce

**Source Code:**

```chapel
// Foo
export proc foo() {
  writeln('foo');
}
```

**Compile command:**

```
chpl --library-python Foo.chpl
```

**Execution command:**

```python
> import Foo
> Foo.chpl_setup()
internal error: setrlimit() failed
```

**Work-around**

Commenting out stack limit check works around this for now:

```diff
index 01f413477d..092623f5fd 100644
--- a/runtime/src/threads/pthreads/threads-pthreads.c
+++ b/runtime/src/threads/pthreads/threads-pthreads.c
@@ -399,8 +399,8 @@ void chpl_thread_init(void(*threadBeginFn)(void*),
     //
     // Cygwin can't do setrlimit(RLIMIT_STACK).
     //
-    if (setrlimit(RLIMIT_STACK, &rlim) != 0)
-      chpl_internal_error("setrlimit() failed");
+    //if (setrlimit(RLIMIT_STACK, &rlim) != 0)
+    //  chpl_internal_error("setrlimit() failed");
 #endif

     if (pthread_attr_setstacksize(&thread_attributes, css) != 0)
```

### Configuration Information

- Output of `chpl --version`: `chpl version 1.24.0 pre-release (add8df033a)`
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:

```
CHPL_HOST_PLATFORM: darwin
CHPL_HOST_COMPILER: clang
CHPL_HOST_ARCH: x86_64
CHPL_TARGET_PLATFORM: darwin
CHPL_TARGET_COMPILER: clang
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: none *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: fifo *
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: bundled
CHPL_HWLOC: none
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none
CHPL_LIB_PIC: pic *
CHPL_SANITIZE: none
CHPL_SANITIZE_EXE: none
z

**Comment by ronawho** [comment]
@ben-albrecht can you check if this fails under linux as well?

**Comment by ben-albrecht** [comment]
@ronawho - I am not getting the error on linux.

**Comment by ronawho** [comment]
Thanks. This might be https://bugs.python.org/issue34602 then. I have a hard time reading python bug reports, so it's not clear to me what version that was fixed in.

**Comment by ben-albrecht** [comment]
Interesting. I am using Python 3.7.0 (Anaconda3-5.3.1). I will try with the latest Anaconda, which uses 3.8.

**Comment by lydia-duncan** [comment]
If that is the case, then maybe using Python 3.5 will avoid the problem?  That's not a long term solution for sure, but it would help narrow it down

**Comment by lydia-duncan** [comment]
I may have misread the bug descriptor as well

**Comment by ben-albrecht** [comment]
> If that is the case, then maybe using Python 3.5 will avoid the problem?

Yeah, they make it look like the issue started in 3.6 based on the version numbers.

>  I am using Python 3.7.0 (Anaconda3-5.3.1). I will try with the latest Anaconda, which uses 3.8.

Still get the error with the latest Anaconda3-2020.11 (Python 3.8.50

**Comment by ronawho** [comment]
I see it in Python 3.9.1 too. Just using the following from that python bug as a simple reproducer:

```python
import resource
s, h = resource.getrlimit(resource.RLIMIT_STACK)
resource.setrlimit(resource.RLIMIT_STACK, (h, h))
```

FWIW if we have a way to detect that we're running inside a python interpreter or that we're in --library-python mode we should just be able to not do the setrlimit. Alternatively we could just make this a warning rather than a fatal error
