### ISSUE TITLE
Installation issue for version 1.25.1

### ISSUE THREAD

**Issue by kurtnordlander** [chapel-lang/chapel#19276]
I was attempting to install version 1.25.1 when 
I tried updating the PATH using the following command:

CHPL_BIN_SUBDIR=`"$CHPL_HOME"/util/chplenv/chpl_bin_subdir.py`

I recieved the following error message:
(its actually the last part of the Traceback)

File "/home/kurt/chapel-1.25.1/util/chplenv/chpl_compiler.py", line 6, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils.spawn'

Any suggestions?

**Comment by mppf** [comment]
@kurtnordlander - which version of Python is your system using? What is `python3 --version`? If it is 3.10 (or newer), we have updated `main` with PR #19168 that should solve this problem. You might try a `git clone https://github.com/chapel-lang/chapel` and see if building that works better.

**Comment by kurtnordlander** [comment]
Thanks. I have Python 3.8.10. I saw that Python 3.7 was required for chpldoc. I thought I was ok.

**Comment by bradcray** [comment]
@kurtnordlander : Thanks for reporting this.  Most of the team is out today for the long weekend, and I'm not enough of a Python expert to know what might be going wrong here.  It looks as though this code has been dramatically refactored since the 1.25 release such that the only appearance of distutils in our `util/chplenv` scripts is here:  https://github.com/chapel-lang/chapel/blob/main/util/chplenv/utils.py#L7-L13

This makes me curious whether working from the `main` development branch would make this problem go away for you, if you were willing to try that.  If not, we may need to wait for the Python experts to return, as the comment in that file suggests to me that the expectation is that `distutils` would be available with Python versions after 3.2 (and Python versioning and dependencies are where I tend to get baffled by Python).

**Comment by lydia-duncan** [comment]
Can you import distutils from a normal python3 interactive session?

**Comment by vasslitvinov** [comment]
@kurtnordlander how is your Chapel installation doing? Is distutils still an issue?

**Comment by bradcray** [comment]
I'm removing the high priority label on this and closing it due to the lack of follow-up information that would permit us to reproduce or diagnose it better.  If someone else hits this and wants to provide more details, we can re-open it then.
