### ISSUE TITLE
Random compiler errors, when trying to call submodule

### ISSUE THREAD

**Issue by rmzs0711** [chapel-lang/chapel#19932]
### Summary of Problem

Random compiler's output when trying to compile the wrong code that calls inner module like a procedure. I have met:
1. illegal type index expression '_unknown()'
2. unresolved call '(DQ�V()'
3. internal error: UTI-MIS-0935 chpl version 1.26.0
4. internal error: AST-EXP-0292 chpl version 1.26.0

Expected compiler's output: " hello2-module.chpl:9: syntax error: near '(' "

### Steps to Reproduce

**hello2-module.chpl:**

```chapel
module A {
  module B {
  }
}

module Main {
  proc main() {
    use A;
    A.B();
  }
}

```

**Compile command:**
chpl hello2-module.chpl 

**Execution command:**
./hello2-module 

### Configuration Information

- Output of `chpl --version`:
chpl version 1.26.0
Copyright 2020-2022 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)

- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: fifo *
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib *
CHPL_ATOMICS: cstdlib
CHPL_GMP: none *
CHPL_HWLOC: none
CHPL_RE2: none *
CHPL_LLVM: none *
CHPL_AUX_FILESYS: none
```

- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by rmzs0711** [comment]
I figured out, that the correct, but useless, code also gives internal errors. Sometimes it is compiling correctly, but just like the example above, gives sometimes random errors

### Steps to Reproduce

**hello2-module.chpl:**

```chapel
module A {
  module B {
  }
}

module Main {
  proc main() {
    use A;
    A.B;
  }
}

```

**Comment by bradcray** [comment]
@rmzs0711: Thanks for filing this.  I've been able to reproduce it on my Mac with 1.26.0 as well.  With the `main`/development branch of Chapel, I'm getting a reasonable error:

```
hello2-module.chpl:7: In function 'main':
hello2-module.chpl:9: error: modules (like 'B' here) cannot be called like procedures
```

so it may be that this is already resolved.  I'm not thinking of what would've improved this offhand, so will do a bit more sleuthing to convince myself we're in a better state before closing this.  Assuming the issue truly is resolved, this fix would also appear in our 1.27.0 release later this month.

**Comment by bradcray** [comment]
Ah, maybe more specifically:

Maybe we can use the CHPL_HOST_COMPILER setting when uniquifying the LLVM build directories (rationale: won't mix and match your .o files) without using it when uniquifying the install directories (rationale: because once it's installed, you probably don't care what it was built in anymore).  ???

**Comment by bradcray** [comment]
Now that I've got my tabs straight again:

* As mentioned previously, I saw this same strange rotating failing behavior on my 1.26.0 build from source on Mac, but not my developer copy of `main`
* Next, I took my developer copy, and checked out 28c0a2476a (which roughly corresponds to 1.26.0) and compiled the program and got what seems like a bogus error, but it was stable and less internal-looking, namely:
  ```
  hello2-module.chpl:9: error: use of 'b' before encountering its definition, type unknown
  ```
  (where, as you can see, there is no variable named 'b' on that line)
* So then I did a git bisect and found PR #19718 (commit 227763f22c) to be the last failing version and PR #19632 (commit c5c36ca955) to be the first working version.  But strangely, I got the same stable bad error above for all failing versions.  And even more strangely, #19632 doesn't seem to change the compiler, just the modules.

The varying behavior reported in the OP suggests a memory error of some sort to me, so the worrisome thing is that perhaps we haven't so much fixed it as ended up in a state where the memory layout is not prone to it.

In any case, I think our next steps here are to:
* run a valgrind/asan test on the cases above using the `main` version of the compiler to see if they're clean
* if so, do the same for a 1.26.0-era version of the compiler to see if it's not
* in either case, add these codes as tests to our test suite to (a) get more testing on them across configurations and compilers (which will include valgrind and I think asan testing as well?) and (b) become aware of the problem should it come up again

Meanwhile, @rmzs0711 : If  you have the interest and time, I'd be curious to know whether, by using a clone of `main`, you also see the problem go away.

**Comment by rmzs0711** [comment]
> Meanwhile, @rmzs0711 : If you have the interest and time, I'd be curious to know whether, by using a clone of `main`, you also see the problem go away.

I have cloned the main branch and built it with ```make```. After compiling the branch I still see an error. But it is not "rotating", now it is always 
 ```
hello2-module.chpl:11: internal error: UTI-MIS-0939 chpl version 1.27.0 pre-release (9f2e40b945)
Note: This source location is a guess.

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug --
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```

**Comment by rmzs0711** [comment]
I want to try a bisect too, but I don't know, how are you using bisect in large projects? I think you are not building the whole project each time you checkout, or are you?

**Comment by bradcray** [comment]
I am.  So it takes awhile on the first few checkouts, but as you hone in on a given range, it typically goes faster and faster due to smaller changes.

**Comment by bradcray** [comment]
Running the compiler with address sanitizing enabled (as documented in https://chapel-lang.org/docs/developer/bestPractices/Sanitizers.html#best-practices-sanitizers) does show an issue, so the bug isn't fixed, it's just that my more recent builds don't run into it.  Thanks for reporting this, we'll see if it's something we can easily fix for this month's release.

**Comment by bradcray** [comment]
@mppf: This  looks to be due to code you added in 2019 to remove dead modules early in the compiler (in scopeResolve.cpp, in `markUnusedModule()` and `removeUnusedModules()`).  With a quick look, it appears as though it's pruning any modules that aren't the main module, named on the command-line, or transitively used/imported by those modules (?).  For the tests in this issue, it appears as though this is having the effect of removing the `B` module (which meets those criteria) before getting to the point of issuing the error that it can't be invoked as though it was a function (which is referring to freed memory due to its removal).  It seems as though potential fixes would be to note that the `B` module is being referred to in scopeResolve and either (a) keep it alive based on that in order to trigger the later error safely, or (b) issue an error within scopeResolve itself saying that it can't be referred to without a `use` or `import` first.

**Comment by bradcray** [comment]
I suppose I should've phrased that as a question:  Since you're more familiar with the code, having written it, do you have thoughts about how to proceed here?  :)

**Comment by mppf** [comment]
@bradcray - sorry I have been trying to juggle too many things and dropped this one.

Here is a patch that does (a) which I think is a reasonable fix in the near term:

```
diff --git a/compiler/passes/scopeResolve.cpp b/compiler/passes/scopeResolve.cpp
index 3702331138..424fb59344 100644
--- a/compiler/passes/scopeResolve.cpp
+++ b/compiler/passes/scopeResolve.cpp
@@ -1436,6 +1436,13 @@ static void resolveModuleCall(CallExpr* call) {
           sym = t->symbol;
         }
 
+        // If sym itself is a module, note that it is used
+        // (relevant for getting an error for the case in issue 19932).
+        if (ModuleSymbol* calledModule = toModuleSymbol(sym)) {
+          currModule->moduleUseAdd(calledModule);
+          storeReferencedMod(calledModule, call);
+        }
+
 #ifdef HAVE_LLVM
         // Failing that, try looking in an extern block.
         if (sym == NULL && mod->extern_info != nullptr) {
```

Obviously we could issue an error right there instead of tracking that the module was used, if we wanted to. I think this is a smaller change, though.

If you are able to help with testing and PRing, that would be appreciated.

**Comment by bradcray** [comment]
> If you are able to help with testing and PRing, that would be appreciated.

I can do this.  But first:

One question about the patch (if you know, otherwise I can try it out):  Does it have the impact of keeping modules alive in the event that they are only referred to by modules that will turn out to be dead themselves?  E.g., I was concerned that an approach like this might cause a program like the following to keep N and M alive:

```chapel
module Main {
  writeln("Hi Michael!");
}

module N {
  ...M...
}

module N {
   ...M...
}
```

That said, I'm not really clear on what resolveModuleCall() gets applied to, so maybe that's the key...

**Comment by mppf** [comment]
I don't know the answer to that question and if you are worried about it, it would be fine to change the patch to issue an error in the conditional.

**Comment by bradcray** [comment]
@mppf: After some delay, I'm getting back to this today.  I tried to create a test case that I thought might now keep a module alive unnecessarily, but was unable to do so.  And reflecting on it a bit more, I think this makes sense.  If the only modules we keep alive are those that are "called", which will then result in an error, then it shouldn't keep anything alive incorrectly.  Here was my best attempt before reaching that conclusion:

```chapel
module Main {
  proc main() {
    writeln("Hi Michael!");
  }
}

module O {
  module M {
    use super.N;
    N.y;
    proc x {
      writeln("In N.x");
    }
  }

  module N {
    use super.M;
    M.x;
    proc y {
      writeln("In M.y");
    }
  }
}
```

I'm running a paratest now.

**Comment by bradcray** [comment]
@rmzs0711 : Belatedly, thanks again for filing this.  You probably saw, but we filed a patch yesterday that should address this and generate reasonable user-facing errors for both cases.  Note that though you called your second example correct but useless, it is not actually accepted in Chapel today.  Essentially, module names are only supported in `use/import` statements or for qualifying other names, but cannot be standalone no-op style statements by themselves.
