### ISSUE TITLE
[Feature Request]: cray-pmi support

### ISSUE THREAD

**Issue by green-br** [chapel-lang/chapel#26917]
### Summary of Feature

**Description:**

When building on Cray machines which do not fit descriptions documented (e.g. XD series).  It would be good to be able to support cray-pmi module to bring the pmi2 library.  At the moment when compiling chpl code it will not find the pmi2 library - I have set LIBRARY_PATH to the cray-pmi location as a temporary fix for this configuration.

**Is this issue currently blocking your progress?**

When building Chapel with Spack I had to make a change to the Spack package to support setting CHPL_COMM_OFI_OOB to pmi2 rather than setting platform to a Cray setting (which does some magic in the configuration).

### Code Sample

In `util/chplenv/chpl_comm_ofi_oob.py` add code to mirror following to query `cray-pmi` package:

https://github.com/chapel-lang/chapel/blob/b301fa0753984dec7e533787a4cfd897c9fb6298/util/chplenv/chpl_comm_ofi_oob.py#L95

**Comment by jabraham17** [comment]
I think having `CHPL_COMM_OFI_OOB` use a better default than 'sockets' makes a lot of sense. For example

```patch
diff --git a/util/chplenv/chpl_comm_ofi_oob.py b/util/chplenv/chpl_comm_ofi_oob.py
index ade8fff3b3e..bd1c34e7be4 100755
--- a/util/chplenv/chpl_comm_ofi_oob.py
+++ b/util/chplenv/chpl_comm_ofi_oob.py
@@ -34,7 +34,10 @@ def get():
     elif 'mpi' in launcher_val:
         oob_val = 'mpi'
     else:
-        oob_val = 'sockets'
+        if third_party_utils.pkgconfig_system_has_package('pmi2'):
+            oob_val = 'pmi2'
+        else:
+            oob_val = 'sockets'
 
     return oob_val
 
```

I think this would mean `CHPL_COMM_OFI_OOB` would just work out of the box, without needing to mess with spack. But, adding a spack variant for ofi_oob is probably also just generally useful.

**Comment by bradcray** [comment]
Tagging @arezaii and @bonachea on this due to the mention of Spack, though the real fix should take place in the Chapel source tree.

**Comment by bradcray** [comment]
@green-br : What interconnect does your XD system use?  And while we check to see if we can get access a similar system, would you have time to see whether Jade's patch above gets things working for you?

**Comment by jabraham17** [comment]
I've been poking at this more, but unless the specific system is drastically different to the ones I have access too more is needed. I am currently testing on an EX and two different XDs. Both XDs are infiniband based machines, not slingshot. 

On the EX, I am trying setting `CHPL_[HOST|TARGET]_PLATFORM` to `linux64`. But since `cray-pmi` does not provide a pc file for pmi2 anyways, my patch doesn't work. The value of `pmi2` can also be inferred from the cray pe compiler, but that only gets used on a hpe cray system (and by explicitly using linux64, I lose that logic). I massaged the scripts more and added support for [`hpe-cray-xd`](https://github.com/chapel-lang/chapel/issues/26918). I don't have a good way to autodetect that (or the network for that matter), but explicitly setting it makes progress.

I have a much bigger patch now, see https://github.com/chapel-lang/chapel/pull/26921. You can get a local patch file for this with `wget https://github.com/chapel-lang/chapel/pull/26921.patch`

**Comment by green-br** [comment]
Hi - thanks for taking time to look.  At the moment the only issue I have experienced using modified Spack package - https://github.com/green-br/buildit/blob/main/repo/v0.23/isamrepo/packages/chapel/package.py - I have set a variant to set `comm_ofi_oob` to `pmi2` and placed a dependency on `cray-pmi` and it compiles.  The issue is when I then go to use `chpl` and it reports it cannot find `-lpmi2` where the `cray-pmi` pkg-config is not found and would need `cray-pmi` instead.  I am using an XD series with Slingshot 11 - see: https://docs.isambard.ac.uk/specs/#system-specifications-isambard-3-grace. The Spack spec I am using is 

```
  chapel:
    variants: comm=ofi comm_ofi_oob=pmi2 host_platform=linux64 launcher=slurm-srun libfabric=spack
    require:
    - "%gcc"
```

**Comment by jabraham17** [comment]
Oh, I think I understand. We determine the pmi library path based on the cray PrgEnv. But by setting `host_platform=linux64` as the spack variant, you are explicitly telling the build system not to try and use hpe cray stuff. You could provide a white lie to the build system and use `host_platform=hpe-cray-ex`, and it may properly detect things. Or, using https://github.com/chapel-lang/chapel/pull/26921 you can set `host_platform=hpe-cray-xd` and you should get the same effect

**Comment by green-br** [comment]
Do you depend on cray-pmi at some point then or does it automatically get picked up if using the Cray compiler wrappers?

**Comment by jabraham17** [comment]
We don't depend on cray-pmi directly. We rely on using a cray-PrgEnv-* compiler and pickup it up automatically from there. For example, `cray-PrgEnv-gnu` or `cray-PrgEnv-cray`. If you have one of these modules loaded and invoke `cc --cray-print-opts=libs` on your system you will see the right pmi linker flags.

**Comment by jabraham17** [comment]
Hi @green-br, I have merged https://github.com/chapel-lang/chapel/pull/26921 which should allow you to use `host_platform=hpe-cray-xd` or `host_platform=hpe-cray-ex` to get the right cray-pmi behavior, and closed this issue. If thats not sufficient, please feel free to open reopen this

As far as spack not supporting `comm_ofi_oob`, I think that should have its own issue, probably on the spack repo. And I think @arezaii is already aware of the issue

**Comment by green-br** [comment]
Hi, thanks for that.  Makes it clearer for the XD support.  However I am still thinking if I were not to use the Cray compiler wrappers (e.g. as suggested here: https://cpe.ext.hpe.com/docs/latest/craype/spack.html ) in Spack it would still not pick up cray-pmi since Chapel assumes the Cray compiler wrapper deals with that.  Where pmi2 is assumed to be the only pmi2 pkg-config name it would need to also lookup cray-pmi?

**Comment by jabraham17** [comment]
I can't speak to what should/should not be done in spack... But after some further offline discussion we came up further improvements to detect `cray-pmi` with/without the cray wrapper and with/without the `cray-pmi` module even being loaded (thanks @bonachea)

See https://github.com/chapel-lang/chapel/pull/26967

**Comment by green-br** [comment]
Thanks - that looks like a great help to get things building without relying on the Cray compiler wrappers to do their magic.
