### ISSUE TITLE
Reductions over standalone parallel iterators

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#6704]
### Summary of Problem

Doing a `+ reduce` over a standalone parallel iterator yields the incorrect result. Additionally, when the iterator yields tuples, the program will not compile (see error below).

As a temporary work-around for the user who encountered this (@npadmana), the `+ reduce` works as expected for leader/follow parallel iterators.

### Steps to Reproduce

**Source Code:**

```chpl
// This program succeeds in compiling, but produces the incorrect result (count == 0 instead of 5)
iter myIter() {
  halt("Dummy serial iterator");
}

iter myIter(param tag) ref where tag==iterKind.standalone {
  forall i in 1..5 do yield i;
}

var count: int;
forall i in myIter() with (+ reduce count) {
  writeln(i);
  count += 1;
}
writeln(count);
```

```chapel
// This program fails to compile due to assertion error in [implementForallIntents.cpp:1125]
iter myIter() {
  halt("Dummy serial iterator");
}

iter myIter(param tag) ref where tag==iterKind.standalone {
  forall i in zip(1..5, 1..5) do yield i;
}

var count: int;
forall i in myIter() with (+ reduce count) {
  writeln(i);
  count += 1;
}
writeln(count);
```

### Configuration Information

- Output of `chpl --version`: chpl Version 1.16.0 pre-release (99f28f5)

**Comment by ben-albrecht** [comment]
I'm guessing @vasslitvinov is the right person to look into this.

**Comment by benharsh** [comment]
@ben-albrecht : it looks like this issue is resolved. Can you verify?

**Comment by ben-albrecht** [comment]
@benharsh - Verified! Do you know which PR resolved this? Also, do you think it would be valuable for me to check in these test cases?

**Comment by benharsh** [comment]
I think it was #7466. Probably not worth checking in, I think there are enough tests that would catch this issue now.

**Comment by ben-albrecht** [comment]
It seems my past self only verified the first program. I'm seeing that this program still fails today:

```chpl
// This program fails to compile due to assertion error in [implementForallIntents.cpp:1125]
iter myIter() {
  halt("Dummy serial iterator");
}

iter myIter(param tag) ref where tag==iterKind.standalone {
  forall i in zip(1..5, 1..5) do yield i;
}

var count: int;
forall i in myIter() with (+ reduce count) {
  writeln(i);
  count += 1;
}
writeln(count);
```

I'll do us all a favor and check in a future.

**Comment by vasslitvinov** [comment]
@ben-albrecht this does not fail for me on master. Would you double-check?

**Comment by ben-albrecht** [comment]
Someone ought to check in a future :)  I'll double-check and check one in when I get a chance.

**Comment by vasslitvinov** [comment]
I am assigning this to @ben-albrecht for creating a future and moving back to "new issues", pending a reproducer.
