### ISSUE TITLE
Surprising behavior for virtual methods with different names for formals

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#7247]
### Summary of Problem
Consider the following program:
```chpl
class Parent {
  proc helper(bar:bool) {
    writeln("In parent helper");
  }
}

class BadNameChild : Parent {
  proc helper(someTotallyDifferentName:bool) {
    writeln("In bad child helper");
  }
}

class GoodNameChild : Parent {
  proc helper(bar:bool) {
    writeln("In good child helper");
  }
}

proc foo(p : Parent) {
  p.helper(true);
  writeln();
}

var p = new Parent();
var bc = new BadNameChild();
var gc = new GoodNameChild();

writeln("Calling with Parent");
foo(p);
writeln("Calling with BadNameChild");
foo(bc);
writeln("Calling with GoodNameChild");
foo(gc);
```

I would have expected this program to call each helper method once, but it actually calls the parent helper twice and doesn't call BadNameChild's helper at all:
```
Calling with Parent
In parent helper

Calling with BadNameChild
In parent helper

Calling with GoodNameChild
In good child helper
```

If I change BadNameChild's helper's formal name to ``bar``, then the program works as I would have expected.

----------

It turns out this behavior is defined in the language spec in section 15.2.5:
> If a method in a derived class is declared with a signature identical to that of a method in a base class, then it is said to override the base class’s method. Such a method is a candidate for dynamic dispatch in the event that a variable that has the base class type references an object that has the derived class type.

> The identical signature requires that the **names**, types, and order of the formal arguments **be identical**. The return type of the overriding method must be the same as the return type of the base class’s method, or must be a subclass of the base class method’s return type

This behavior is very surprising to me, but I don't know the rationale for this section of the spec. I can see how there would be complications with named argument calls, but we could emit a compiler error if the formal names are different.

Two questions:
1) Should we keep this behavior?

2) If we keep it, can we emit some kind of warning to try and avoid surprising users?

**Comment by benharsh** [comment]
I believe we should only consider the types and order of the formals when looking for a virtual method match. Once we find a match, we should emit a compiler error for any formals whose names do not match the method they override.

**Comment by mppf** [comment]
@benharsh - I think we should solve this problem by adding an `override` keyword (or something along those lines) to indicate where the author of the subclass is intending to override a parent method. I think that would help in this case but also in several other cases I've run in to:

 * overriding generic methods can be tricky/unexpected
 * sometimes you just put in the wrong number of arguments, the parent class's method changes, or you misspell the procedure name.

**Comment by cassella** [comment]
There is an `override` keyword now, and applying it to `BadNameChild.helper()` causes a compilation error.  It doesn't note the name of the argument as the reason.

When the `override` keyword is not used on `BadNameChild.helper()`, `foo(bc)` continues to invoke `Parent.helper()`, without any warning.  So the original surprising behavior is still present, though now it requires two user errors to get there: mismatched arg names, and the omitted `overrides` keyword.

**Comment by benharsh** [comment]
I'm glad that the override keyword catches this, so I'd be fine with closing this issue.

I think the error message could be more helpful:
```
foo.chpl:8: error: BadNameChild.helper override keyword present but no superclass method matches signature to override
```

Some further description of why the method could not be matched would be helpful. Maybe a separate issue?

**Comment by mppf** [comment]
@benharsh - I'd like further description of why any resolution fails, e.g. if I call myFunction(arg=1) but it's `proc myFunction(x:int)` then I'd like the compiler to say that the named argument did not match. (Or if the types don't work, which argument that's happening on, etc). Implementation-wise I think such an effort would be needed to handle the override missing case here.

**Comment by mppf** [comment]
I think #7658 covers the error message part, generally. I'll add a note about this case.
